### ISSUE TITLE
Error in SplittingStreamPowerLaw branch

### ISSUE THREAD

**Issue by jeanbraun** [fastscape-lem/fastscapelib-fortran#16]
@benbovy, I have found a memory/assignment error when running the version with split StreamPowerLaw and FlowRouting routines, which I cannot figure out. I propose to rewrite this branch from scratch being more careful on how to split the routine. By creating two versions of the StreamPowerLaw (one for single donor flow and one for multiple donor flow) we should increase clarity and most importantly speed (in the case of single donor flow). I will soon create a new branch with these modifications at which point we should abandon (erase) this branch.

**Comment by benbovy** [comment]
> By creating two versions of the StreamPowerLaw (one for single donor flow and one for multiple donor flow) we should increase clarity and most importantly speed (in the case of single donor flow)

Mmm unless you'd like to use different variables to store information about single vs multiple flow receivers, donors, etc., and/or unless I miss something important, I think that the approach used in #14 (i.e., split StreamPowerLaw and FlowRouting routines, with one single version of StreamPowerLaw) is more clear. Otherwise you will end up with a lot of duplicated code (SPL solver).

I'll try to look at the memory/assignment error in #14. The error only happens when using Python bindings, right?

**Comment by jeanbraun** [comment]
To be correct it happens mostly (and much more often) with python bindings and for single donor flow (p=-2). But I have also run into memory/assignment errors calling it from Fortran.

**Comment by benbovy** [comment]
Closed in #23
